### ISSUE TITLE
script location

### ISSUE THREAD

**Issue by matenhagen** [pkainulainen/Examples#1]
Convention is to store scripts at src/main/scripts and not etc as show in  Maven / assembly-plugin

See <scriptSourceDirectory>src/main/scripts</scriptSourceDirectory> as specified in the super pom, http://maven.apache.org/guides/introduction/introduction-to-the-pom.html.

**Comment by pkainulainen** [comment]
I was not aware of this convention. I will move the scripts to the src/main/scripts directory.

**Comment by pkainulainen** [comment]
The scripts are now moved to the src/main/scripts directory.
